version: '3.8'
name: jeanbezerra-performance-lab

services:
  springboot-api:
    container_name: springboot3-performance-simulation-api
    image: springboot3-performance-simulation-api-image:latest

    ports:
      - "443:443"
      - "8081:8081"

    volumes:
      - C:/TEST_DUMPS/:/opt/software/dumps

    environment:      

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    depends_on:
      - postgres-db

    deploy:
      resources:
        limits:
          memory: 2g

    restart: unless-stopped

  postgres-db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: